# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    #service_name:
    #    class: AppBundle\Directory\ClassName
    #    arguments: ['@another_service_name', 'plain_value', '%parameter_name%']

    importer.csv:
            class:     AppBundle\Service\ImporterCSV
            arguments: ['@doctrine.orm.entity_manager', '@validator']